# Generated by Django 4.2.21 on 2025-05-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='img', upload_to='categories/'),
            preserve_default=False,
        ),
    ]
